name: Build & Deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: GagnatDev/scaleway-gh-action/registry-login@main
        id: registry
        with:
          secret_key: ${{ secrets.SCALEWAY_API_KEY }}
          region: fr-par
          registry_namespace: ${{ secrets.SCW_REGISTRY_NAMESPACE }}

      - name: Build and push Docker image
        env:
          IMAGE_BASE: ${{ steps.registry.outputs.registry }}/unforked
        run: |
          docker build -t "${IMAGE_BASE}:${GITHUB_SHA}" .
          docker tag "${IMAGE_BASE}:${GITHUB_SHA}" "${IMAGE_BASE}:latest"
          docker push "${IMAGE_BASE}:${GITHUB_SHA}"
          docker push "${IMAGE_BASE}:latest"

      - uses: GagnatDev/scaleway-gh-action/container-deploy@main
        with:
          secret_key: ${{ secrets.SCALEWAY_API_KEY }}
          region: fr-par
          container_id: ${{ secrets.SCW_CONTAINER_ID }}
          registry_image_url: ${{ steps.registry.outputs.registry }}/unforked:${{ github.sha }}
